### ISSUE TITLE
[Feat] MainView 상단 ‘하루만 끄기’ 토글을 추가합니다. 

### ISSUE THREAD

**Issue by bluehyudawn** [DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch#40]
### 📝 작업 목적

 MainView 최상단에 '하루만 알림 끄기' 토글을 활성화할 수 있도록 합니다.

---

### 🛠️ Tasks

- [x] 토글 추가하기

**Comment by lianne-b** [comment]
확인했습니다:) 고생하셨습니다 알렉스! 
pull request 열어주시면 메인 브랜치에 머지해놓을게요!

작업 브랜치로 옮겨가서 > open pull request > create pull request 해주시면 되어요👍

<img width="480" alt="Screenshot 2023-07-30 at 4 27 53 PM" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch/assets/89244357/1b7f9c77-7414-4281-a7a1-9b14b2dde49f">


<img width="1217" alt="Screenshot 2023-07-30 at 4 27 44 PM" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch/assets/89244357/9a68b77b-41c1-4e16-ae63-7b82ed4761ca">


<img width="1042" alt="Screenshot 2023-07-30 at 4 28 07 PM" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch/assets/89244357/13c0e7b1-6841-49c8-b5c5-3f26663934f4">

**Comment by bluehyudawn** [comment]
끼약 덕분에 완료했습니다! 감사해요

**Comment by lianne-b** [comment]
앗 호옥시.. 이슈 넘버 41도 부탁드려도 될까유..? 감잠다 흑흑ㅋㅋㅋㅋ🥲

**Comment by bluehyudawn** [comment]
저 커밋은 2개로 나눠서 해놓고.. pull request는 한번에 뭉쳐서 해버린 것 같은데요(...)

**Comment by bluehyudawn** [comment]
<img width="1255" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch/assets/45624895/fc2dc836-3330-46c3-a8e7-c62bb1ca7be1">

**Comment by lianne-b** [comment]
오 그렇다면 오히려 좋은..?! 감삼다....!! ㅋㅋㅋ 메인에 머지 완료 되었으니 코드 잘 들어가있는지 시간 되실 때 함 확인 부탁드려용👍

**Comment by lianne-b** [comment]
<img width="361" alt="Screenshot 2023-07-30 at 5 01 11 PM" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch/assets/89244357/9d888617-e07e-4a08-a715-8da912806bb7">

일단 제가 보기엔 너무 이쁘고 완벽합니다,,
